- platform: noaa_tides
  station_id: 9413745
  time_zone: lst_ldt
  unit_system: english
  name: "Monterey Bay Tides"
- platform: template
  sensors:
    nextsunrise:
      entity_id: sun.sun
      friendly_name: "Next Sunrise"
      value_template: >
        {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
      icon_template: mdi:weather-sunset-up
    nextsunset:
      entity_id: sun.sun
      friendly_name: "Next Sunset"
      value_template: >
        {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
      icon_template: mdi:weather-sunset-down
    jc_date_and_time:
      friendly_name: "Date and Time"
      value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%A %B %-d, %I:%M %p') }}"
      icon_template: mdi:calendar-clock
    jc_day:
      friendly_name: "Day"
      value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%A') }}"
      icon_template: mdi:calendar-today
    jc_month:
      friendly_name: "Month"
      value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%B %-d') }}"
      icon_template: mdi:calendar-month
    jc_time:
      friendly_name: "Time"
      value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%I:%M') }}"
      icon_template: mdi:clock-time-three
    jc_day_night:
      friendly_name: "Day/Night"
      value_template: >-
        {% if is_state('sun.sun', 'above_horizon') %}
            Day
        {% else %}
            Night
        {% endif %}
      icon_template: >-
        {% if is_state('sun.sun', 'above_horizon') %}
            mdi:weather-sunny
        {% else %}
            mdi:weather-night
        {% endif %}
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
- platform: template
  sensors:
    weekday:
      value_template: "{{ now().strftime('%a') }}"
      entity_id: sensor.date
      friendly_name: "Day of Week"
    newdate:
      value_template: "{{ now().strftime('%m %d %y') }}"
      entity_id: sensor.date
      friendly_name: "Today's Date"
- platform: template
  sensors:
    lastfm_currenttrack:
      friendly_name: "Current Track"
      value_template: >-
        {% if states.sensor.herm71 %}
        {{state_attr('sensor.herm71','last_played')}}
        {%endif%}
      unique_id: lastfm.currenttrack
    lastfm_toptrack:
      friendly_name: "Top Track"
      value_template: >-
        {% if states.sensor.herm71 %}
        {{state_attr('sensor.herm71','top_played')}}
        {%endif%}
      unique_id: lastfm.total
    lastfm_total:
      friendly_name: "Total Tracks"
      value_template: >-
        {% if states.sensor.herm71 %}
        {{state_attr('sensor.herm71','play_count')}}
        {%endif%}
      unique_id: lastfm.toptrack
- platform: template
  sensors:
    # Music
    album_count:
      friendly_name: "Album Count"
      value_template: "{{ state_attr('sensor.hermserver_library_music', 'albums') }}"
    artist_count:
      friendly_name: "Artist Count"
      value_template: "{{ state_attr('sensor.hermserver_library_music', 'artists') }}"
    last_added_music:
      friendly_name: "Last Music Added"
      value_template: "{{ state_attr('sensor.hermserver_library_music', 'last_added_item') }}"
    last_timestamp_music:
      friendly_name: "Last Music Added Time"
      value_template: "{{ state_attr('sensor.hermserver_library_music', 'last_added_timestamp') }}"
    # Movies
    last_added_movies:
      friendly_name: "Last Movie Added"
      value_template: "{{ state_attr('sensor.hermserver_library_movies', 'last_added_item') }}"
    last_timestamp_movies:
      friendly_name: "Last Movie Added Time"
      value_template: "{{ state_attr('sensor.hermserver_library_movies', 'last_added_timestamp') }}"
    # TV Shows
    last_added_tv_shows:
      friendly_name: "Last TV Show Added"
      value_template: "{{ state_attr('sensor.hermserver_library_tv_shows', 'last_added_item') }}"
    last_timestamp_tv_shows:
      friendly_name: "Last TV Show Added Time"
      value_template: "{{ state_attr('sensor.hermserver_library_tv_shows', 'last_added_timestamp') }}"
